//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODetail
    {
        public int PODetailsId { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string Terms { get; set; }
        public Nullable<int> CashDiscount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
